In [ ]:
from google.colab import files
files.upload()

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [7]:
test_df.head(3)

   SampleID                                               text
0    103811             Scott Disick Plans To Return To Rehab
1    207637  A Forgotten Watch Is a Timeless Gift Funny, is...
2    151717  Mycobacterium Marinum Infections From Aquarium...

In [8]:
train_df.head(1)

   SampleID                                               text     label
0    139768  Take a Presence Power Break (The New Coffee Br...  WELLNESS

In [11]:
train_df.iloc[1]['text']

"Yolanda Hadid Returns To Social Media After 9-Month Break For Depression, Lyme Relapse Hadid's last post before her break was from October 2021, the same month that she accused Gigi Hadid’s then-boyfriend, Zayn Malik, of shoving her."

In [13]:
len(train_df)

56727

In [12]:
# Term Frequency-Inverse Document Frequency Vectorizing

from sklearn.feature_extraction.text import TfidfVectorizer

X_train = train_df['text']
y_train = train_df['label']

X_test = test_df['text']

vectorizer = TfidfVectorizer(sublinear_tf=True, lowercase=False, stop_words='english')

X_train_trans = vectorizer.fit_transform(X_train)
X_test_trans = vectorizer.transform(X_test)

In [36]:
# Light Gradient Boosting Classifier initialization + training

from lightgbm import LGBMClassifier

model = LGBMClassifier(objective='multiclass', n_estimators=300, boosting_type='dart', n_jobs=-1)

model.fit(X_train_trans, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 6.174035 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 254711
[LightGBM] [Info] Number of data points in the train set: 56727, number of used features: 7844
[LightGBM] [Info] Start training from score -1.407081
[LightGBM] [Info] Start training from score -0.689013
[LightGBM] [Info] Start training from score -1.374082

LGBMClassifier(boosting_type='dart', n_estimators=300, n_jobs=-1,
               objective='multiclass')

In [37]:
y_preds = model.predict(X_test_trans)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [31]:
pd.DataFrame(y_preds).value_counts()

0
POLITICS         7408
WELLNESS         3638
ENTERTAINMENT    3136
Name: count, dtype: int64

In [38]:
pd.DataFrame(y_preds).value_counts()

0
POLITICS         7383
WELLNESS         3643
ENTERTAINMENT    3156
Name: count, dtype: int64

In [25]:
# Verification

len(y_preds) == len(test_df)

True

In [39]:
# Submission DataFrame building + downloading

S = pd.DataFrame({
    'SampleID': test_df['SampleID'],
    'label': y_preds,
})

S.head(1)

   SampleID     label
0    103811  POLITICS

In [34]:
S.head()

   SampleID     label
0    103811  POLITICS
1    207637  WELLNESS
2    151717  WELLNESS
3     27926  POLITICS
4    115640  POLITICS

In [40]:
S.to_csv('submission.csv', index=False)
files.download('submission.csv')