In [4]:
from google.colab import files
files.upload()

Saving level-1.zip to level-1.zip

{'level-1.zip': b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\xaf\xdd\xd6\x9d=\x00\x00\x00H\x00\x00\x00\x18\x00\x00\x00in_level-1_0-example.txts\xf2\x0f\xd0\tI\xcd-H-J,)-JU\x88>\xb4\xc19V\xc7\xa3473%\xb3\xa4R!Z5\x96\x97\xcbP\xc7\xc8@\xc7\xd0\x94\x97\xcbH\xc7\xc8\x04\xcc0\x861L\xc0R\x06\xbc\\\x00PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\x1b\x93\xe5\xf0U\x00\x00\x00W\x00\x00\x00\x12\x00\x00\x00in_level-1_1-a.txts\xf2\x0f\xd0\tI\xcd-H-J,)-JU\x88>\xb4\xc19V\xc7\xa3473%\xb3\xa4R!Z5\x96\x97\xcbP\xc7\xc8H\xc7\xdc\x88\x97\xcbH\xc7\x18\x88,y\xb9\x8cu\xcct\xcc\xcdy\xb9Lt\x8aS\xcbR\xf3JRS\xf3t,\x80\xe2\xa6:F\x16:&@\x95\x00PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\xae\xd9\x1a}9\x01\x00\x00\x1e\x02\x00\x00\x12\x00\x00\x00in_level-1_2-b.txt-\x91=ND1\x10\x83\xfb\'\xbd;lC\xe7\x952\x93\xc9_\x0b\r\x1d\x14t\x88\x02\x89-(\x90\xd0j\xb7\xe0V\x9c\x81\x93\xf1%\xd0Y\x19\xdb\xe3qn\x1f\x1e\xf5t\xfa\xf8<\x9d_/\xd7\xf3\xe9\xf0\xfc\xf3}\xf7\xa2\xfb\xeb\xc7\xfb\xdb\xfb\xe5\xeb\xf0|\xf3\xb2oU\xb9\xa9\xf8\xbe5YR\xb6}\xeb\xb2\xae^\xf7m\xc8\x86|\xec\xdb\x1c\x0c\xf5\x89\\\x91\xd5&\nF2\xf8VdM>Q\x95W\xb5\x0e\xc2\xa4.[,rV)\xfb\xe6I\x7f\x0b\xdc\xe4\xa1\n\xcd]\x19Z\x03\xc1Q\xcc\xa7\xa6\xa1\xc6v\xc7\xa2\xa8\x05h\xe8\x98\x17?\'1wl\xb3\x8b\x04\x99 9\xd4V\xb60\x11\x8dY\x10\xd2V\xb4(\xea\n,\xa2\xea\xc8+\xb6\xd14\xb5\x98\x05\xc7\xa5\xb5\xaa$\x1dC\x03^q\xdc\xd5H[(\xc6V\xb4\xd29\x0e\x11\x88\x83\t\x02\xaf2\xe5\x98\x0c"\xa6\xab\xf0\xd6\x8a\xbc,EC\xa1\xca\xfe\xc6\x8a\xae\x8a\xb4\x838\x11\xc1\xc0+\xd4\x99\x8e,SG9\xe8\xa8\xac\r\x96fp\x8d\x04\xa4\xc0\x808!\xd2X\xdb\x8c\xe2r\xff\xff\x00n*\xcb\xc8j\xd1\xd1\xd4&\x81\x144\x9af\xa3\x14\x9a\xf8\x1a*\xe2\x03)\xc5\'\xec&Z\x99\xbf\xfa\x0bPK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\xfe\x97\xcb\xf4\xd7\x03\x00\x00g\x08\x00\x00\x12\x00\x00\x00in_level-1_3-c.txt-\x95=\x8a\xddI\x0c\xc4\xf3\x81\xb9\x83\x93\xcdz\xa0\xa5\xfeN\xedd3;\xd8l\x98`a\'p`X\x8c\x1d\xec\xad\xf6\x0c>\x99\x7fU\xfd\xe0\xc1\x13\xfa\xab\xd5%\xa9J\xfd\xf1\xf3\x97\xf2\xd7\xfb\xb7\x7f\xdf\xbf\xff\xfd\xe3\xe7\xf7\xf7\x0f\xaf\xbf\xfe\xff\xf4V\xfe\xfc\xf9\xed\xeb?_\x7f\xfc\xf7\xe1\xf5\x8f\xb7\xe7\xa7\x88\xd2V\x99\x1d\xab\x95\xa8%\'\xd6*\xfc&V\xf6\xd2N\xc9\xc0\x1a\xa5\xb5\xb2\x12k\x96<%\xf8\xda\xa2\xc4.\x1b\x1f\x9f\xb0\xe6\xc6"n\x963\xb0f\x89S\xa6\xac%\x9f\x8c-W\xd7\x01\xb2r\xc5y~\xea\xd5G\xb9\xa2\xb7\xc2}\xb9\xb0\xba\xa0\x04\'\xfaV\x9c|#\xca(\x0b\xd7 l\x02\x0b\x8b0\x00\xea\xe3\x10\xa6\x05\xa6\xb1\x08\xeb\xb8f-\xd5\x07g\x94U:\xd0f\xaa\x98N\xa9\x93\x14ih\xd3)f\xc3"E\xbd\'W\xe1V\x1d8\x821\xea\xf3\xd3\xaa\n\x1b\xe4_!@\x8b$+UU\x00|\xb5B+6I\x16\xe9\xe8\x92N\xd0%\x10\xeb\xab\xd2-\x8c]\xcbK\x96\xcd\xd1-H*y\x93\x03 4d7\xb9@\xb4\xd5\x82\xd2H\xb1\x87Pv\xf9\xa6,\x01\xd9\x8c\x86\x1c\x14\xbf\xb7\xf0\x06\xbeC\x9dx1Ra\xc1\xc7\xd3\xcb\x05y\x86`4\xae:\xf4\xac\xdf0\xa5\xe70\xd6\x16p}\x8dZ]\xfe\x96\xe9>e\xca4\'\xd6\x92\t.\x06\xd0d\x0e\xa5\xd2\x04\xa2\xce\xd2)\xd3\xb1\x9er\xda\xbb\x85r\xd9\xabLPGL\xabn\x89\xbcb]\xb8\x03A\xa0\xf8!\x02\xd2:\xe8#\x16\x05\xdd~ieV\x99Cm\xf3\xc5\xb0\x92d\xcb\xde-\x8e\x1a\x03\x94\xe2\xd8Q\xdet+\xf4\x9d\x9bH\xe7z\xd2\xf58\x94\n\xe0\x8e\x9dn\xe9\xb4\x93\x9e\x86\xe9\x1e\xb9\xc5\xa3\xe1\x80c6*\x97z\x94&I\xf0\x8fwX.\xcd\xd4\x192i\xec4\x01\x02$\xe0r\x06\xba\xd1\x1f\xcaZ\x9e\xa9\xda\x88\x04\x84\xc0\xdf\xdd\x1a\xf7\x03\x11\x08\xa5b\xbbEe\x19v\x03\x1f6a,^\x07t\xb5\xd1p\xbbi\xdfm.\xe9S|\x0b4\xc3|\x97\xbd|\xbd7\x8cj\xc1\t\x02J"\x818\x14#\xd5%\xb7N\xb2\xaa\xe5\xa8\x86a\n\xba2\x84\xd5\xcb\xd1\xb5\x03\xfe\x98\xc6\x81\xc4\xa8b\xa9\x84\xb15\xbc\xe1CGc\x12\xbf\x02\xe9\xb5G\t\x88O\x9bC\xa9$\xbf\x87\x93\xffv\x07\x82\xfe\xd4\x03\x7f\x9f\xe6\x9a\x13,5\xa9\xab\xf7s\xa3\xe7\x9b\xd5cv\x85\xcbL\x12\x00\xe4\xa8\x8e{iq\xfb\xb8\x13\x95 \xc9j\xb3\xcb\xeb\xd6/_\xe0\xb2\xd0d\xcb\x87\xb9e\x86\x93\x1d\xb1\xd2\x0cF\xabq%\x1a\x88\x95\x998v[\xf2C\xc9\xd0\xab\xd8h\xaf\x95a\x15]\xc9jw\x844\xdb.\'$\xda}\xcb\x91j\x1f\xa4\xd9G\xc8\x14z<\x1b\xc3=\xa1S\xdaB!5\x8f;1\xe4\x0c\x01L*\x04\xbd\xae6\x8f\xf7k\xd7\xb5G+\xa6\xeb*\x14=/c\x8ev\xf4]\xd8h{x\xc9d\r%\x12\x92D\xcf\xdb\xca\xcejQ\xe8PJ\xcefN\xa2fQ\xab\xc9\xd464\xcb\x125/O3\xc3\xcb,lFy\x89\x87\x99~C\xb6L\xaf\xe9n\xaf\x1b\x946}\x97\xa4\x94\xa0\x83;Z\x87)%/\xd30\xc3\x0b\x7f8\x83\x07\xae\xd9\xa76\xdd\xb9\x17K\xd8\xcb4HZ}\xcc\x9d\xa4g\xe9\xb9$\xdd\x05W\xf7\xa1\xe9\'\xcb\xdf\xad\x0e-\x8e\xa4\x94eI\xa4^\xb1\xee-\x99\xda\x87\xd3\xe3\xce\xe6\xb6;\x7f\xf3>j\x8aE\xe1\x04\x84p\xc3\x00\xc5(W\xf3`C\xf7j\xc3\xb0\x13\xfdfV\x89\xca\x19 \x8e\xde<\xc5\xf64\t\xec5\xff]\xee}\xe9$\xa0D\xcct2\x1c0\xfd\xa08\x80\xb7\xab\x9a\xe0\x89\xae#\xeeH\xbao\xd3S\x96\x08\xfb\xe1\x1c\xf7iR\xeb\xd0\xb5\x16\x9c\xcdf1:\xd4\x9b\xc3h\xd05\r\x1d6\xfd\x1c\xf82\xe4\xcc\x80\xc2\xb1~\xa0\x8f\xd0H\xceq3H\xce\xdbTO\xe4L\x03\xc5\xef\xdfPK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\n\x0e\x1fvz\x01\x00\x00t\x03\x00\x00\x12\x00\x00\x00in_level-1_4-d.txtE\x92=NdA\x0c\x84\xf3\x91\xe6\x0e$\x9bM\xd0\xfei\xb7\x9d.\t\x19\x04d\x88`\xa5\x9d\x80\x00i\x85 \xd8[q\x06N\x86]\xde~\x9b}\xf2\xabW.\xbb\xfd\xf3\xfe\xe1\xf2x}\xfds}\xfb\xf5\xfe\xf1v\xbdy\xfa\xfa\xbc}\xbe\xdc}\xbc\xbe\xfc~y\xff{\xf3\xf4\xe3\xf9|b\x8b\x0b\xc5E$\xd1g\xe1\xf4\xf3Ix\xa1:\x13\'\xaa\xeb|\xd21@\x96(\xfd]\x0b\x1d\xc8\x89\x01\x01\xa5v\x12\xaa\x8b\xce\'#t\xd0\xb451h\xd3\xc1&\xb4\xb3\x04\xde\xbei\xb6D\n9\x05Ky\x0b\x96A`\xabPQ\x8dD\'h\xb9\x90w\xd5\t-VV\xdd\x90\x9c\xd2\xc1\x03\x02OA\x10\x90\xb3\x1a\xb3\xb5\xb3\xb0\xa7H\x01\rF\x08\xb5b\xc3\xa0\x94vDm\x1dZ\xac\xbe;f\x19\x03.p\xe0_\x19\xc9\xd2#\xd6\xe0$\x86\xae\x06v\xf8\xcc\xf2\xd7\xde\x08K\xb1\xf6Sd2\x9aL\x87\xe749\xf4\xd6\xe9geX~,\x96\x9cz\xf5\xcd\xc7\x96\x93\x91\xdf\xcb\xd3Y\xf7\x12\xc8\xfb\xd5\x0c\x9a\x7f9\xc1\x0e\xbdU\xfe\x18\xb2\x8f\x80\x82\xc0V}c!\xdb\x140\xf2H\xf5\x8d\x80\xbf\xe6\xbf<T\xf7\x93\xf1\xe8\xddV\x06\x1e\x86l\xa4\xe08\xf4\xc4\xfb\xca\x98Zn\xb3\xb8_\x1e\xf2\x9c\x1d\xeb\x87\xbc\xd7)\xe0\xa0=.s\xdb\xd7\t3\xff\x8f\xc62|_Er\xb7\x8db\xf7\xbd~\x96\x00ki\xb4\xd7_\xf7\xcd\xaac\x8f\xcb\xda\x9e\x01\x94}]\xac\x81\xf4\x9c\xf5oPK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\x97<\x948\xe2\'\x00\x00\xcca\x00\x00\x12\x00\x00\x00in_level-1_5-e.txtM\x9c\xbd\xce-=R\x85\xf3\x91\xe6\x1eH\xc8\xf6+\xb5\xcb\xff)$d\x10\x90\x8d&@\xe2\x0b&\x18\x84`@\xe2\xae\xb8\x06\xae\x8cZ\xcf\xaa\xdeg\xa4#\x9dz{\xbb\xddv\xb9\xbc\\U^\xf6\xdf\xfd\xe3?}\xfe\xf9\xb7?\xff\xfbo\xff\xf1/\x7f\xf9\xaf\xff\xf8\xedo\xfe\xf0\x7f\xff\xfb\xf7\x7f\xfc\xfc\xc3\x7f\xfd\xf9O\xff\xfa\xa7\xbf\xfc\xcf\xdf\xfc\xe1o\xff\xf8\xfb\xdf\xb5\xfe|\xce\xf9\x9c\x9e\xe2\xed\x9f\xf8\xb4\xf8\xfd\xef\xe2\x89O\xc4g]\x89\xfd\xb3>s\xa5\x14\xf3\x13\xcfg\xec\x14{\xfb\xec\xfbYM\xe2\xf9\xec\xf8\xf4|?\xe6\xfa\xb4\'\x0b\xab\x86\xd5?\xe7\xb3\x1eI\xe3s\xefg\xa8\x865?}\x7f\x9a\xca\xae,;>mJ\xdc\xaa\xf7P\xe0|\xa2}\x96\xc4\xfd|beq\x89M\x9f\x98z-\xffo\xad\xb9\xf0\xee\x9f\xfc\xd7\xd4\xc8\x9dU\xe5\x07\xf5\xb9=\xf3\xd7\xcf\x1e\x12\xd7\'\xbb4\xd4\xca\xbd?g|:b\xf6\xf63\xd4\xc6\xecBV\xa1g\xe7QU\xa1\x97N~\xecq\xcbO|\xb2\xb6\xa5\xa2\'?\x94\xfdQs\xb3\x9e\x9fp\xdf\xf5\xa1\xfe\x99j\xe3\xd9\x9f\xff\xfc\xed\xbf\x7f\xfb\xb7\xbf\xfc\xf6\xdb\xbf}Bm\x92V\xdb\xa7\xf3\xf6U\x0f\xb7:p\xb3[\xe3s$5\xbdL\xebn|\xf4\\\xb5g\x83sD\x06\x05\xe8TCL\xd5\xe7\xe7%\xa5\xde\xa6\xd5}\xb7>\xc0\xd7\xef\xc9\x0f\xb9y\xa9\xeb>\xa8\xb6?\x8f>;\x1f\x89Y\xf0sCR\xa0\x1fIY\xf9B\x7f\xfd\xc91j(\xa5?\xf3\xb3\xeb\xe1RGcI\xdc\xfa\xfe\xa0\xa6\xa3\xa1w\x81+\xa5n\xbd\x95c\xd2\xb2\x12jh!\r\xaa7=\xdb\xdfs\x10\x8f\xc4!e\xcazzv \x1b.m\xf7l@V\xac\xa1\xedm\xab\xe1\x8b\xd7\x0e\xa3\xc5k|\x83\xee\xc8Hli=\xb0\x08\x9a\x96v\x9a#\xc7\xef]-\x93\xeaz\xaa8\xab\xdb\xfc>\xb3e\x07\xa3\xebiP\xd9\x04\xa4|\xf2\x19\xeaD\xe4\xd8|\x96^J\xbdg{C]H\xfb\xee\xd7]H\xbd\x8e\xe7\xd3\x11\xfb\'\x07bR`\xa8-\x87\xd7\xa6t\x8fB\xba\xea\xd70w\x99y\xfeS\x17s\x82\xb4T:\xedR\xa5\xf9\x9a\x1eg\xa5YB\xc6\xd5G\x93q\xf1\xde\x88\xcfO\xf6MZ\x1a]\xcd\xd9\x94\x1d\xd2(=\x1f\x93\xda\x0e%\xd6\'\x87W\x1f\x1e\x9b\xae\xab\xbf#\xc7i|\xa6\x142\xae\xe6\x18\x8d\x9c\xf9z\xb3\x1ag\xd3\'\x96*\x989R\xdb\x836;s\x05q\xc8.\\\xd6\xb3\x94\xa7\xcc \xeaR\x87\xb2j}mj\na\x17+\x87<\xa7\xa0\xdeZ\x8d\x91D\xe4\x0bGmLD\x10:,dM}&Y_\xccWT\x92\x98\xa0\x01\xd6\xd7\x84\ti\x01\x94M\xc3\xf7\xa0\xad+\x83\xa4\x8d\xa9\x8e\xb4&\xcd\xb3\x9e\xe8\xd0<>\x02\x89\xb47I\xf9-\xcf\xd1\x9e\xd0\x90\xaa\x99jx\xbe\xf13@\x89\x9e\xd0\x90\xcau\x01\x0f\x15\xe2a\xc2PC\xaa\xd3\xb6`l\xa0\x0b\xd9\xba\xd4\x0c\r\x14 <\xf5\t\xe9%\'\x90\x9ax\xa6\x94\x8bj\x8eZ\xfd\x99\xeaX\x82CZ\x89E\xa1\xcf\xe6\xad\xfb\xd5\xf8e\xa2\xd2\xf2\xab\xbe|\x96\xea\x12*\xa49\xa9gW \xcc\xd4\xb8\x1aPwG\xa0\x90\xdfP\xad\x89\n\x89\x06L\xae\xfc_\xff\xf4\x85Kw\x98\x1b\x89\neL\xe3Q\xfbx:\x1e\xe6\x0e\x0f\x05\xfd2\xd1!(\xd84`$\x14HISb\xbe\xb1\xb1\xcb\x91X\x90]\xbc\x8fD\xb0 (\x90\xbdq\xa5\xed\x01\nB5\x08\xaa1\xec\xd146\x1a\xe5!\xa0\x1e\xc0\xda\x90u6\x00d\x08\x13\xb25\x14\xc8\xb1i\x80\xd5h\x8c\x8d\x10l\x08~?S\x9fJHhF\xd3\x91\xdd\xcb\x11\xe5\xf7\x00\xb7\xa5\xe3\x91S,\xdf\xba\x88\xd9\xaf\x8b\x92Gx\xca\xaa\x06aB*W\xd2\x02\xc2(\x9a&\xc70\x0f\x81\xc3\xa9\x92|\xab\xa9\xdf\t\x0fY\x93\x1e\xe6LR\xa5zI\xe8\xe0\xae&8x\x82\x8d\xb4\xfd\x0e\xb6\x8c\x1c\xc9jR"C\xbe\xb2xx5\xach=1 mV\x95\'\x04\xe4\xc8\xd3\xbdA\x95R\x8f\x10``,C\x08\xd0\x81\xa91\xd0\x94\xe6\xe4H\x00P?\x10\xb7\x1a:\x11S\xe5\xae\xf4J\x0f\x9a\x92#\xe7\xbf\xa6\x8e\x1a:\xb5\x14\xf0\xf9\x9c\xfe\xa9\xb5\xc9\xc3\xfe\xf9\xe9\x9a\xdd#g\xbfVyU4\x855 \xc5H \xf04\x1e\x89\x039\x8fhi\x02A\xb6{\xf3\xd6\x95Yj\xe1\x1e\t\x04Z\x834&\x8b1aP\x13\x08\x04\xaezm\xe9\x7f\xe6\xd6\x10\x0eh\x95R\x13\x12\x08T\x1bU,\xcd~:\x9e@ \x15Q\xdb\xe1\xa9\x9a\x93H\x10\x8b\xe9?\x84\x04\xd7\xed\xd9\xb26t\x9c\xaf\xdcV\xbfw\xd93\xcd\x91\x97\x90&?y<\xa5[M\x93\xb1\x019l \xb1 \xc7\xc6U\x1c\x96\x10IW\x95Q4\xb1`\x0c\x9b1+\x98\xa7L\x0e\xc7\xc5S\x19\x89\n5\xcaGf\xe1\xde\x9c\t\xf0\r\n,,\x9e\x12[\x83\x87\xed\x1e\x8d\x98`e$(4\xaf\xe9\xe3z\x9eJ5\x89\x04\xdd\xde\xd4H$\xc8f\t\xe9\xc7\x15@y\xc8/k\x90\xc0h\xc8AX,w\xe3j\xc6Z\x8d\t\x05\xf9W\xf0\xda\xd5\x92+\xb0\x99\x8f\xa6*-\x9f\x8f\x17p\xf9\x81\x13X\x98<\xedi\xc0\x814\x00\xf2!QV-Wjf\xaf\xd2\x9a\xe5\xc4M\xa3\x82\xccfj\xb5\rf\xf5\x94\x87`om\xe6\x87\xb4\xe4\xa9\x82\xecal&\xd5l\x01\x9c\xe9\xab2\x0f\x940\x9b\x17 \xde\x9aR\xad>\xd0\x18%> O!+F\xbc\x18\x90\x86a\x1a\x0c\xa4\xb0\x19\r} fS\xdc\x19\x8d\x073t\x1a\n\x84\xd23-Q\xee\x8c\xeaJ\x8bZ\xf5\xfbV\x03\x84\xbc3U%K\xa2\xa6\xcb\x9a\xa3\x02\xc2\x82\xed\xaf\n\x0c<_f\xf7\xe2\xad.\n\r\xb2\x9b2\xbb\x99x\xf0\x80\xa23\xf1@O\x83\xc2\xcc]\x9a(g\xc1S~\xe60\x0b\xd0\xa8\xe2jJ\xca\xdc\xe7`J\tr\xe7\xb0\xe7}%j\x98\x06\xbfwi1\xf8}\xc8\x95\xdc\x88\x13\xcc\xd0\xc7\x04\x14\x8f\xac_23\xeaP\x03\xeevG\xbc\xb2W\xa1\xd6\x9cr\xc6\xfd\xb5\xc4\x8a\xfc0mO\xb0\x10F\xf3\xb4\xe3-\xf2\x14\xafn\xf2\x9a\xcc"x\x98f\xd1=\x94\x93\xae\xa9g\t\x16\x02xD\xc0\x82\x97\x12,\x9a\'\xdc\\\xf6\xe9\xd4\x9f\x85\xe3M\x05\x8a#\x16>\xcc\\\x98\x05*]\xf3\x1dJA\xc5\xc3L\x9f\t\x158\x8e\x12\x0f\x9fE\xcc\x8f\t\xeag\x02E\xb3\xd79\x13(\xba\xdd\xc3\xa9\x80\xe2\xb1\x839S[\xf8u\x12\x99\xbe\x98\x8d\x90"\xedxQz\xb1\xc8\xa8\tr\x1b\xe6\x87\x02\t\x83@\xeb\xdcvV\xd5\xd8C\xc7\x18HE\x01\xac\x16S\x01Ega\x99\x87\xe0\x05[\xd1j\xf8T\x01\x86\x0c\xcd\x1e\xe6\xb1\xc0{\x1e;\xfa<\x05\xdb\x91\xae\x9a"\xd7k^<\x14\xb9|\xf32`\x8cB\x82F8R\x98\t\x1a\xb2*D\x06\x8ca\xbc\xf3u\xb7\xe6\x95\xe9\xfb\xe1~c\x9e\x99\x98\xa1\x11Wo\x14\xc0Qr=\x98\xa2`b=\rH\x98\x12\xf9\x96V\x82\xf5`\x8b\x03Qz\xa57+1\xa3\xd3\x96\x95\x98\xa1%\x1dq\x0b\x07,\x9e7\x96Y\x0f\x1d\x13>-\xa9\x05m/9\x12\x83\xd9\xb2\x04\x19 \xd9j8\xfc\xbc$\xc8x\x0cE\xcb\x981$\x11\x9f\xb9\xec\x96\n\x16u\x1d\xe1\xa6`q\x85M]\xd5\x86\xe1V\x15\xc8\x7f\xf0\x1cZ\xc2\x8c\xc7]\x10h,&\xd9R_\x1d~\xac\xc0Y\x19\xd4\x00\xa07\x9e\x1e\xccGm\x10jxHW\xa2\xc6b\x8a\xad\x8e\x97\x87B\xfb\xeb\x83\xadn\x07Y\x9a\x93\x0b\xe1@ze9\xa3\xf5J\x93M \x08~\x07biK\x07bQR\xfe*?To\xa5\xde\x05\xbc<UA\xf7q\xb0<!\x8d\xaf\xc4\xd2\xa1i\xb7\x12%\xee\xc5\xba\x96\xdc\x89\xc6\x14]\xe3\xbca\xe8\x1a\x84/B\xf65\x99B2\xda5\x03\x1fJ\x12\x03\xd2x\x88\xc3B\x0f&\x1e\xfe\xa2\xc0b\xc1Qo\x12\x19\xae\xe1m%4\x14\xbc\xadi\x18\xd2k\x8b\xc5I~\xf9ZX\x1aC*?\xe2\xb8\xde\xd51/uB\xd0@|\xbc\x12\x19\x9a\x9d\xe2\xa5p\x02\x0cX\x89\x0c\x0f\x13x%0\xc8\xecy\xc7K\x87\x10i1\x93lI\x9boY\xc4\xdd\xc7\xaa7\xf1\xbf\xd6\xed%h8V8\xcb\x81?\xb1\xc1\xa1\x8d\xb8\x01Mj8`\xb8Z+l\xf0\xe0\x1d\xdc\x14\xfd|pT\xb1\x88C\xb4\x87\x99\x08\x0f\xbc\x98\xaf\xf3\xf5\x8a\x17A\x92\xe7U\xe2\xc1f\x11Y\x07P\xa5\xb1\n\'\xfc\xbe\xa2\x89c\xe3\xc2o\xb1\x8an\xe0n\xa8*\xf9\x10\xadD\xbc=\xe1\xef\xb2\x0f\x81f/FM\xb3\xef~C\x9ee<\x98|\xe2\xe2\xf8\xa7F\xf7#\xa3\xdeHMoi\xf4\xf7\xc3\xb2.\xa8\xde\xc2\x03\x7fw\xb3\x02}\x16\xa2\xacz#i\xa9\xc9A\x91h_oKd\x1d\x94\xbe\xb7|\x08&\xf6&\xb2\xa0\xb1\x9b\x0f\x11t\xef\x16o\xc2g\xcb\x85\xd8\xc4\xc6\xbb\x91\x01\xd0|\xdf\xca\x97\x1c\x90tk8\x131$\xe1\x1b\xf9\xf7\x83\xa1Q\xc1\x05\x0fT4\xf0+56[\xd0\xe0\xd0v\x0b\x1a\x8cC;\xf0\xce\xa5\x99-h`6n\xb2\rD\x90\xdb\xc80)\xba\xa5\x83MQb\xb2C\xb5d\x854\xf5\xb7\xfc\x89\x06\xd4\xee\xde\xdea\xd8=\x80\x19\n\x90\xa0\x91\xef\xb1\xfb\xac%`\'D\xe4\xe4\xa6\xe7\x9a\x8b\xcc\xab\xdd\t^hag\x9d\x95Mly\x10\xf8l;\xa7\x8c\\\x16\xe9h\x10\xf3\xf3\xf3\xf8\x90\x13\xda\x95^\xa0\xa6\xa1u\xd7:\x1e\x8a(]\x80\x95\x95\x91Ux1q\x9d\xf6DY\x9aa{\xca\xbaQ\x80\xc2\x8b\xcbK\x93q\x99\x88\xd8\x80f\xcf6.\xf0p\xd1Qu_\xe1\xc5\xc3\x04\xdd\t\x0b?N\xac\xec\x89[,X\xd8J.8\xa6\xd8r\x13p\xcd\xf6\xd2$sS\x96c;~\x97\xfb\xec\xbe\xac\xfd:\xee;!@!\xbat\x91\x10\xb0\x1d^n2V\xael\xcb\xdf\xb3\x06\x95\xd9\xdc\xd6\xb0\xb3\x8d\x9b\xb2\xe3M&\xee=__wo2sZ\x0e\xf7&\x06g\x0c\x13\x01\x1cm\xed\x8dmaPJ)<\xa0\xf3>\xf8\xf3\x8c\xbc\x13\x8b\xa86\xe7\xfd\xc0\x01\xder\x03\x1e;\xa8\xfb\x10\xe31\xd740OM\x0be\x17\x1b\xcb\xff\xc6\xf5\xb3\xca\x14>T\xb0\xb3\x95I\xb8\x9exJ9<\xb6Z\xa7\x12\xb0\xa9KF\x0e\x0b\xcf\xb9\x1f^\xdb\xb6\\\\\xeb,\xa7\xbe\x12E\xfa\xdae\xd4\x85>\xe7!\x85\xa5\x02\xe7\x01h\xe4\xd2\x1f\x99\x8f;w\x1ey\xdc\xb2\x8a\xa3\x84@#\xd28\x0fSd \x82ir\x0b\xceC\x06k\xf2\xd6!\x03\xcbS\xa6\x88\xfc\xcf\xd3\x9e7\xcf|\x1a\xf92\x99\xd3ixTZsOc>^I\xac\x06rv\x8f\x0ctb\xed\xa7)\xbe\x97\x0eN\xc3\x86\x17\x0f\xaf\x16ZD\xe6"\xea8\x81O/c8\x11\xaf\x7fyB\xc1\x90V\x96\xa3\xf4"\x00}bV\xc0w\xe2\x1b\x9f\x9c y\xd5x\nfn\xea\xbfo\xaa\xe1H?\x0e*N\xf70\xc9\xef8\x9d\xe5\x80z;\xae\xa8F\xfd\xf0?\x00z\xe43`\xb9G\xd1\x83!\xe7t4\xa7U\xea\xf4C\x9a\x96\xa2W\xa0\'\x988\n\xbb\x9c\xf88\x03\xd8\x94\xd3x\x129\xe47\xe8\xb5\xe1l\x19O\xf1{i\x82\xf3\x0c\x16\x17+8"6\xc8[\xe7\xd7[\x97eJ_H$\xc8\x8fh*\x1f!\x81=\xc13Y\x0fh\xd8T\x9eD\xa8x\x04\x05\xd5\x82I\xa6I\xa6\x7f&.\xb6\x9c\x98\xa3\xe0\xe1y\xdc\t\xf9\x08\x1e\x9ci\x9bP\xd9\x85\xc3#O\xee\xaco\xc6\xf6,\xf2fZ\x05\xce\xf2\x82\xa0\x91X\x04\xb0\x9aS\xa7\xd2\x0b\x88v\xad\xd50\xc7\x0c\x98(\xae\xc1`\xda\x9e\xed\xb1R+7\xd0\x89\xbd\x13\xa9x0\x155\xd8\x18\x13\x17\x9c\xc0>\x86\x05\x8c-a\xe1\xc7\xb8q\x04\x0be\xd8\x9bx\x1cs\xdfNg\xa9\x13\xc6\x05\xfa{\xb0q:|\xbc\xe7\xc1\x8c9\xb2AyJ\xe78\x85J\x01r\x19t\xe2`\x85\x93\x1a\x9cB\xa5\xac\xb2\xdd~\x8bl\xb7z\xaeE\xd7\xfe\xd7\xd1\xca\xb2\x98\xddG\xeb\x81M\xe5\x0e\x0cH\xfd\xbe\n[\x89\t\xcee\xb5F\x1b\x97p\xabS\xd7!p\xe2\xb5\xab\xac\xa7\x9c\xaakxP\xb3\xefCl\'\xd0\xber\r\xf0&\xefC\xceIVs\x1f\xa0\xe8"\xe2[+&\xbd\xdaK\x02\xd7\xee\xc3\x02\xcaK\xe0)u^\xd4"S\xba8\x8a\xe0\xd7m\x04\xc8\x17\xb1\xbfq\xd3\xad\xf8`QX\xe0ji\xb1\xec.\x89r\x11\xf5\x01\xf5\xa9\xd5\xfb\x8az\x94s\xbbv\x06\x04\x8a7\xb1\xe1z\x13\xe1:\xcf\xa8\xa1\xbd\x01\x8c\xf3)\'\x17\x06e1k\x1e\xe2\x1e*\xca\xbc\x0e\x13\xfc;\xde\xa8\xa6\xc5U\xa2q1\xb7o\xa2\xc3v\xa3*\xb7\xa0o\t\x1b0\xce\x9b\xd0\x10^\xd5/\x1b=,\x967\xa1!\x17\x8f\x8b\xe8`_#\x7f\xfb~\xb7\x80\xae\xc0aV\xe1+\xeb\x13@]\xb9\xbd\xd8\xf1\x1d\xec\x0b\xd0\xc4\x11\xf8\x7f*:\x9c\xe7\xa69\t\x0ed0$N\xa6\xa6\x8c\xfd&:T\x9a\xe9\x8e\xfd\xba4w\xe0\xe84\n\xb0\xcc\xcahn\xc2Cs8\x7fg{\xb1\xfdN\'NT\xc3\xd4\xbe!\xa3?\x89\xb7d\xa0W\xf0pXeob\xc2dB\xdf\xe9I*\xd1Y\x04\xba\xb6\x18\x1e>\x9b8 gJ\xdfZ\xca\x9f\x0f$\xfb\x1f\xfc\x8e\xca\xd0i"\xc2;\xe8\x8b}\x0e\xba\xb0\xe8\xc2\xe2)Q\x16J\xdf \x9c\xde\x92\xa3`\xdd\xeexwZ\xee\xc6\x12\xf8\xeaf\x99\xe0\xf7\xa9\xf8Z:\xdc\xf8l4E\x19\x04O\x8f\xed\x8c\x99$\x1c\x1d\xe1\xfe\x15\x18lf\xf5u\xae\x91\x99p\xe2\x85\xbc\xcb\x16\xc4\xb1%\x1dr#L+mAL\x96\xc4{\xd6\xeb\xb8\xdeSX\xca\xe3\xf35\x1be\x11<\x9d.\xeb+\xc3a<\xd0\x12\x7f\xd3sX,j\xf7\xe2ba\x8b\x97-\x15->\x97\r\n\x16\x94{\x17\x1bO\xd4\x05\xaa2J\x97`\xdbO\xf1\x1c$fK\x181-\xd1)\xe3^K%)\x870A\xc0\x992\x1b\x05\xc7\xb2S\xb7\xdb/\x83w%\xb3g$lJ\x99\xdc\x85\x06)\xe5C\x1e\x0c\xd19U\x8a4r\x84|\n=\xe3P\xa4L\x0c\xe1\xa6\x91\x87\x94\xaeS\x1c\x1f\x87\x13)N<+W\x82\xb5\x0c?\xcf\x05\x1bU\xa4\xc8\xea+g e\x12\xd4\x1dYS\x98\xd9\x98"\xd6y\xa8<H\xa8mZ\x1b\xf2\xbf\'\xcd\n\x99J\xa7nmN0\x90)\xca\x15k\xb4\xd5\x19I\xf7\xd2\xa8\x11\xc8\xdd\xfb.\x9b&v\xef\'\xf0\xae2\x0c\x1d\x93O\xb9\x97\xe7\x92\xa2!\xd1\x9d\xee,X\x83F\xf6\xf5\xaeB)\xcbi\n\x179\x15\xe6\xa7x\xb1\xbcI\xf7\xe4^\x10=\xa5\xd8\xbeY\xcf\xfc\x03\xd7\xccU\x0e\x12\x03\xdb\xe5\x9dG\xa1\x99\xa36gi\xe7 m\xe8\xf6\x0f\xc2\xce\xe1\x17\xc8\r\r:?p\xa2\x0fm\x9b\xe0$R#\xe2\xa5\xc4\xb4G\xe8\x12\xbd2A)z\xf9\xa75\x82\x93]\xbd"#\xe1p>\xffp\xf0\xe1\x1f\x8e\xa6\xd1\xa0e\x93p\xd7\xd6\x9aX\xf3\xe3\xad\xcb\x94\xdbg\x97\x1d.\xfc\xc4E\x13\xe0>x4\x97wni\xcd\x9a\xaf\x83\x912+\x8fu\xbc\x0e\x11\r\x83\xb2\xee\xeb\xc0\xb7\x87\x17\xddA3 \x06\xaa\xf1\xdeF\xa3\x1a\xf5\xb4fH\x82\xcd,\x85)w\xeaDu\xca\x8bL\x13\x1f\x12J\xd7\xa0y\xa7\xb3\xbb\xf2\xab\xe0\x8f\x0e)k\xf9\xac\x1a\xa8cg\xd12{\xfa6\x9c\xa3\xee\x05\x1f=D\xd9V\xbcr\x97\xefc\xfcE\xebT\xc9\xcb\x1a\xed\x03U\xc4\x13\xfd\xe8\xa3n\xb9\x1c\x8a]F\xa3\x9e\xcdj\xccujvS\xfb\x95\xe3\xe3N\xdf\xc1\xc6)#\x93\xb3I\xde\x15\xdd\xbbJ\xd9\xbf\xc57~\xac\xeb\x91\xcb\xe0\xa9pY\xf8\x04r\xad\x15;"\x90I\xfah\xa9o\x82\x99\x8aOR\x96oG-\xa4\xcf\x97\x01 \r\x82\x9dY\x17YEtI\x91\xdd\xca\xee\xc7d\xcdh\xa4f\xd9q\xaa?g\x07\xa8~x.\x04\xf2\xfck\xcd>+\xb5\x93m\xb3R[\xc3~\xdc\xb06_\'$\xe5\xfdR(R>\xd2\x9f\x16\xee\x94q\x8e\x19\xee\x16\x06\x84\xc6\xcb\xc1\x12\x82b[h\x87\xb1\xb9L\xa7\xe3\xd4\x13\xa3\xf6\xf2Sd\xa7\xbc\xf3)\xb9\x86\xf5\xd5\xf8\xa2A\x93\x0b\xd2\x8dH-Q\xe81\xd6\x89M\xf4\xe3`%e\xa3\x01\x13\xa1u/\xc6\xd4\xae\xe0\xa6\x13S\xa5Lt\x83\xf1\xb7\x8e\xeb\xb7\xf9\x946L\xeb\xab}\x97\xcb\x97"\x0e\x93\xd5\xd1\xef\x9baL-\xe5\xf7\x99)M\xe9\x8dn#o#\xde\xc08e\xbc&\x8f\xfc0\xf2m\xbf:\xb5 /\x17Zo\xee$em\x97\xe1]\xa6|?\xdf\x8e$\xeaD-Dmb\xad\xdd\xcf\xc9\xafa\xe8mj\xf7\xc33\xa7M\xfctkg\xc2\x7fbb\xb6\x04\x9e\xfbV\xc9\xde\x99{\x05\xb9b\x95\xf9i\xa3\xc4\x96\xdb\x14\xea\x18\xe8\xdb\x92\xcbZ\xf6!\xd8YU\xa3\x92 \x13\xe7>e\xd4jke\xb3\xc4V\xb0\xc8QXg\x8bH\xce\x8d\x14\x04\x154\xb4\r\r\xc6e6iw\xdb\xc4f\x07\xd7\x16\xa4\xacz\x10\xe3\xa7\x8c\xef\xbe\\\x9ep\xdbJ\xdb$\xfa\x87\xe5/\xf2\xb4\xe2X\xb88\x1b\xd4tJ\xde\x8e\xd7\x81&\xc3\xae\x85\xb1\xe5\xbc\xd1\x9e\x1e\x1f:\xfdMg\xa5\xacP\xcb\x9a9\xa0\xb9M\xee\x14\x9a\xf3\xd1D\x1e\xef\xd2\xa7xphQ\x93B\xa0[E\xbcs\xe2\xb6;W\xeaQ\xb88\xc0\xee_\xc2\x8d\x9a@\xe3\x99\xf5^\xbf\xdb\xb5\x9bmK\xb8(\xb3\xbb"\xed\xd14\x97a:\xd2\xf1\x90\xf7e\xef \x9c-\xc1nD\xb5\x93%/d\xbb\xf6.\xc3\xcc\x07\x1d\x82l)Kl<$\xe50\xddx\xf6\x17\xcd\xe2as\x1c\xd3\x8d\x07\xb5\xfa\xb9Z\xe5\x9c~\xca\xda\x88rc\xcc\xd1B9!\x9c\xb2Z\xa3\xd9l\xf8h31\xa7!\xf3\xd5\xee2\xfbe+\xa5\x8c\'\xe9\x067\xf4\n\xba\x87:\xed\x857\x04<5/B\xc2\xc1MN\xb9\x13L\xd3o\xf2.^w\xc52T\xb0\xf0 \x93\xae\xc5\xd2Ca\xd3\x13\xd5\x0634\x80\xbc\x80\xc0\x15\xd4\xd9\x81\x01J\xc8\x01*\xeb\x0eH\x1a\x0cr8xb\xbeD73\xc8\xcf\xe7KGL\x99\xb5\xb9\xf9\xd5\xfd]\xa7a::\x96J\x99\x9d\x10\x8c;\xe4\x009\xdf\x9e2i\x08\xa6u\xc8\x01rR4e\xa7Z\xe9\xe1\x18o\xb27\xe5I\xe0K\x9dl\xd2\xd6@(\xe1j\xd3\x8aq\xde<L\xca\xb8\xd0\x1e\xd9\xf9\xbc[S)7\xca \x12\x94\xb22\xc4\xec/\x85 \xe5\xf1fERv\xba\x85\x16\xc8\x01*\xf5M\xa7-]D<\xa5\xe9Z\x1ch\xbb\x9a\xc5\xce7\x0bw\xac\xf6f\x80R\xd6\xd0\xd8C\x11\xf7\xd3T\x8f&\xf2\xa7\xb6\xddh\xd9\x9al\x8a\xf1)\x01\xd1\xf3\x94\x15\xad\r\xfa\xb8\x1eF\xd6\xef2yXB\xc5\x06\xad\xad\x98&:\xa8\xb8*4A!\x8b\xe7i8\xf0\xb2\xbdnRK\xee \xb1\x97GV\xb9\x98r\x9d\xc4\x08\xbde+\x1b\xfa\x85\x9f\xa2`\x16\xbep\x00\xe6\xb11&y\xbc\x95\x8f\xf1\xd2\x04-tU\x13\x155z\xb1\x89\x84\xa4\xfb\xb6\xf0\x90\x84\xde\x96\xbdC\xe8ZH\xa9zX\x89\xc2\xac\xa4\x0b\xb1\xcd\x96}\xd98\xb6\x18\x0c0m\xb9d\xa2\xfd\xa6\xc0\xa9b\x1b\x91D\xfb*\xe3\xb8\x80\xafg\x91\xe8/Q\x90q\xcf\x8b\xb8"\x8a\x86\xfdg\x11E\x9b\xe3\xb5\xd6\x1f\'$\xc1\xfc\xee}]%\xd3\x9b\xe8\xa2\xc7\xcb\xb0\xe8\xa2Z\xab\x17\xf2,\xa2\\\x13a\xb4\xf8J\r\xc6h5X\x94\xd1A\xa0\xdeD\x19\xbd\xe6\xca\xa4{\xf0\x8d\xda\x9b\xf8\xa3J>Pc\xb3\xdf7\xfd\x07\x1e\x98\xcbx\xff\xdf\xb2\x10qX$K4\x11\xd9\xb5\x04wz\xf3B\xea\x164\x98\x83\x0c\x8eh\xa4\xbb\xd6\xc3\xce\xee\x9d\x8dCDR\xc7\xe8MLR!\x98\x8b{\xc3\xdc\xc5\xc1&\x7f\x16.)p\xde\x03\xe6*K\xb6\x88\xa

In [5]:
!unzip 'level-1.zip'
!rm 'level-1.zip'

Archive:  level-1.zip
replace in_level-1_0-example.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: in_level-1_0-example.txt
replace in_level-1_1-a.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

# LEVEL 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Level 1-a
df1 = pd.read_csv('in_level-1_1-a.txt')

In [ ]:
df1['Temperature [°C]'] = df1['Temperature [°C]'].replace('seventeen', 17)
df1['Temperature [°C]'] = df1['Temperature [°C]'].astype('int64')

In [ ]:
df1['Temperature [°C]'] = df1['Temperature [°C]'].astype('int64')

In [ ]:
df1.sort_values(by=['Temperature [°C]'])

   BOP  Temperature [°C]  Humidity [%]
2    3                 6            77
3    4                17            89
0    1                22            72
4    5                28            42
1    2                32            39

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BOP               5 non-null      int64
 1   Temperature [°C]  5 non-null      object
 2   Humidity [%]      5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
# Level 1-b
df2 = pd.read_csv('in_level-1_2-b.txt')
list2 = df2.sort_values(by='Temperature [°C]', ascending=False)['BOP'].tolist()
list2 = list(map(str, list2))

In [ ]:
with open('submission2.txt', 'w') as file:
  file.write(" ".join(list2))

files.download('submission2.txt')

In [42]:
# Level 1-c
df3 = pd.read_csv('in_level-1_3-c.txt')

In [49]:
sorted_temp = df3.sort_values(by=['Temperature [°C]', 'Humidity [%]'], ascending=[False, True])

In [50]:
sorted_temp

     BOP  Temperature [°C]  Humidity [%]
145  201                43            40
138  194                43            58
58   106                41            52
126  181                41            65
185  247                40            16
..   ...               ...           ...
152  210                -2            15
166  224                -2            42
67   115                -2            73
37    80                -2            84
66   114                -3            60

[200 rows x 3 columns]

In [51]:
sorted_temp = sorted_temp['BOP'].tolist()
sorted_temp = list(map(str, sorted_temp))
" ".join(sorted_temp)

In [53]:
with open('submission3.txt', 'w') as s3:
  s3.write(" ".join(sorted_temp))

files.download('submission3.txt')

In [55]:
# Level 1-d
df4 = pd.read_csv('in_level-1_4-d.txt')

In [56]:
df4.head()

   BOP  Temperature [°C]  Humidity [%]
0  269                19            33
1  285                19            58
2  327                19            35
3  355                19             7
4  400                19            76

In [59]:
df4['Temperature [°C]'].describe()

count    73.0
mean     19.0
std       0.0
min      19.0
25%      19.0
50%      19.0
75%      19.0
max      19.0
Name: Temperature [°C], dtype: float64

In [57]:
sorted_temp = df4.sort_values(by=['Temperature [°C]', 'Humidity [%]'], ascending=[False, True])

In [58]:
sorted_temp

     BOP  Temperature [°C]  Humidity [%]
3    355                19             7
56  2125                19             7
70  2472                19             9
20   865                19            11
71  2473                19            11
..   ...               ...           ...
53  2058                19            81
21   892                19            89
43  1824                19            89
59  2161                19            90
27  1116                19            94

[73 rows x 3 columns]

In [60]:
sorted_temp = sorted_temp['BOP'].tolist()
sorted_temp = list(map(str, sorted_temp))
" ".join(sorted_temp)

'355 2125 2472 865 2473 1067 2066 2160 490 1810 912 781 1436 2388 733 2495 1193 2162 1449 438 269 437 2421 327 1903 636 1816 2191 1972 2272 958 1994 2069 2398 1023 1850 619 1350 1789 2309 650 742 1971 2440 1612 1386 1563 285 2266 764 782 1148 1887 1913 2158 1838 760 2044 1362 518 816 2308 680 956 400 1169 1521 1817 2058 892 1824 2161 1116'

In [61]:
with open('submission4.txt', 'w') as s4:
  s4.write(" ".join(sorted_temp))

files.download('submission4.txt')

In [81]:
# Level 1-e
df5 = pd.read_csv('in_level-1_5-e.txt')

In [82]:
df5['Temperature [°C]'] = df5['Temperature [°C]'].replace('seventeen', 17)
df5['Temperature [°C]'] = df5['Temperature [°C]'].astype('int64')

In [83]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2171 entries, 0 to 2170
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   BOP               2171 non-null   int64
 1   Temperature [°C]  2171 non-null   int64
 2   Humidity [%]      2171 non-null   int64
dtypes: int64(3)
memory usage: 51.0 KB

In [84]:
df5['Temperature [°C]'].describe()

count    2171.000000
mean       39.853984
std        36.325644
min        -5.000000
25%        10.000000
50%        22.000000
75%        79.000000
max       113.000000
Name: Temperature [°C], dtype: float64

In [85]:
df5.head()

   BOP  Temperature [°C]  Humidity [%]
0  130                88            83
1  193                 2            12
2  202                22            69
3  203                 6            56
4  225                20            47

In [86]:
sorted_temp = df5.sort_values(by=['Temperature [°C]', 'Humidity [%]'], ascending=[False, True])

In [87]:
sorted_temp

       BOP  Temperature [°C]  Humidity [%]
2036  2359               113            13
1638  1944               113            22
1187  1480               113            37
1709  2018               113            40
1351  1647               111            16
...    ...               ...           ...
1759  2072                -5            47
777   1060                -5            60
1701  2010                -5            65
1698  2007                -5            66
1075  1365                -5            76

[2171 rows x 3 columns]

In [88]:
sorted_temp = sorted_temp['BOP'].tolist()
sorted_temp = list(map(str, sorted_temp))
" ".join(sorted_temp)

'2359 1944 1480 2018 1647 1330 2260 1509 535 1259 533 1041 882 1585 909 1644 1131 272 1768 2187 2002 786 614 358 1553 2061 2104 1034 2401 2036 914 575 1144 1417 325 788 1045 1764 2032 1413 1566 983 1056 1186 1039 2386 1337 2385 1645 1508 633 1581 1398 1336 2486 2202 1776 485 1158 256 1471 1650 1318 363 2099 1080 2152 2118 1686 1345 1638 1784 959 546 1849 1120 2193 410 869 936 2062 572 311 1935 1312 1781 1831 2234 1562 1030 1092 2442 2151 1196 501 2476 831 1227 745 1301 338 1682 474 791 383 2282 1343 1004 943 345 464 2294 1806 1579 1900 1937 1499 2012 2443 1858 669 1592 2493 1908 519 2174 1529 945 2345 1266 1967 2496 2130 857 987 1407 1928 2240 2123 1963 1515 591 460 2015 1309 264 2310 2305 1483 1794 792 551 2350 677 646 600 2221 2102 540 658 2447 1872 939 2133 498 1870 473 2244 2319 2436 1705 2410 396 530 2406 878 777 1257 1618 1748 2009 404 1099 1207 1615 1260 1620 2248 1347 1719 397 1412 1538 2048 961 2392 2253 439 1958 1489 2340 1629 2255 921 928 333 2215 2358 1138 1815 477 1411 2461 2353 392 1105 1723 1021 1112 668 1922 862 1254 1964 743 1375 1664 1675 276 353 389 1389 1094 1429 1467 1805 1243 1733 2369 2424 2030 1501 657 890 1285 2101 747 801 1072 1236 734 528 2322 472 2107 2214 1201 2404 304 691 553 1028 1422 1857 1495 1344 1859 441 1031 1191 1066 1237 1911 2291 1384 916 730 1244 479 1956 1008 1462 2208 2247 2373 292 1377 896 1726 1947 1439 2121 2387 2086 1231 1985 877 544 2190 1356 2094 706 1888 746 543 1835 794 702 1995 2334 1216 2376 2467 2379 852 739 1183 1797 1466 1418 603 851 512 394 559 1174 459 1401 1206 1415 2016 130 1895 1245 1624 904 302 755 1332 1782 1720 1953 2451 624 1044 1161 2347 2471 1446 779 1086 1364 1554 1012 1527 846 2177 655 1653 2186 275 712 2355 954 2060 1215 2159 365 1049 563 2184 550 719 620 652 1038 357 2363 1841 1321 1845 413 967 1474 2126 277 774 806 2084 318 2181 1171 319 1584 579 686 2445 1481 1949 611 1611 1661 1677 1643 860 982 309 1492 426 829 1902 1608 1986 2284 1003 1597 2055 640 384 1251 907 1729 445 524 2198 1862 1530 1388 2173 366 595 320 415 685 849 1659 558 1914 1556 924 1578 1482 703 688 1292 845 1248 1441 1006 2042 1109 727 2045 2014 2119 424 334 1610 1605 830 315 1117 1448 870 1833 288 2180 2242 1884 2413 1440 1472 1339 1685 1532 2299 1424 1048 969 1593 639 1514 2425 867 587 913 297 608 842 2273 1361 1724 1834 2477 1904 414 2332 486 1721 641 795 509 997 716 1059 525 653 2049 308 994 1683 408 699 920 1115 1871 1226 1340 1912 347 323 1348 720 807 2035 1234 470 2176 613 374 1891 231 1880 1665 750 1242 1498 541 1565 837 1043 1391 1547 1454 1674 911 1660 1320 1225 2354 2135 949 1992 2080 1646 661 1054 2246 352 1807 1325 798 2295 864 1879 1368 2124 769 1820 1488 1689 1822 980 1526 671 1469 717 1288 1123 2141 1101 497 946 1195 504 601 1110 362 1280 1468 2499 2383 1939 2313 529 1476 1338 2397 370 1894 1892 2417 562 1918 1383 2046 1943 995 1290 1666 1007 314 2381 2068 2453 2028 457 554 1351 282 597 1163 1393 2027 1877 1096 1458 2249 594 1696 1324 1400 1505 2047 2474 1945 1052 812 273 2239 280 616 2017 1747 2438 2420 1042 2033 291 2423 585 629 1976 1998 590 654 1139 2302 2067 2318 286 1760 1477 2112 2156 2269 1293 545 1190 2051 2201 444 773 1494 583 582 380 2087 440 763 1916 2138 1402 732 321 625 561 756 2034 1546 238 810 901 2128 1447 1713 1989 2074 905 1681 1071 993 1088 1803 1793 271 1669 1444 1649 2004 990 467 1135 707 1846 547 1015 1395 2116 790 1069 312 344 461 1064 609 1513 589 1842 1212 623 1250 2073 576 1238 1966 421 1984 1204 2452 1374 281 2484 1082 808 1114 1960 2275 1445 880 1036 1707 780 1825 2411 757 1899 1057 856 1832 1766 1308 1957 348 996 480 767 1534 1128 2277 1741 899 1609 1567 1743 386 976 1843 1399 1909 1145 736 2263 970 850 663 604 1218 2321 1959 2143 2025 1866 465 2371 458 2341 934 988 510 637 1627 793 332 2059 1777 670 1443 1910 2267 2217 1813 1734 1475 506 1573 2147 331 861 1746 1569 1419 1241 1210 1202 517 1486 1550 492 839 894 715 1704 265 2053 1155 651 1621 1267 1168 2057 772 571 1652 313 634 1295 819 1560 1762 1070 944 1075 1885 631 1421 1076 1262 1331 387 391 1304 1651 2144 833 2021 1727 299 1327 361 1536 317 1955 1965 1893 573 898 1373 1133 556 2349 1032 2317 1141 1046 1954 2219 335 2428 1596 2179 645 1801 1153 1366 695 731 495 521 298 1856 1297 1625 2296 1694 2498 741 1132 1717 962 350 1016 2070 2200 1670 2437 2370 1591 1672 2256 871 1223 918 966 1906 1715 1068 761 293 2013 1639 2298 802 2434 2390 752 1997 1346 2274 1428 423 2148 431 1219 1974 1189 2262 1780 2320 2077 1757 1662 436 295 2375 1233 690 1051 499 1678 307 838 933 1203 674 316 1143 1018 1540 1799 1978 1787 1557 1867 1222 1999 1299 511 1463 1580 1090 1708 1118 1586 2085 1897 607 2064 753 1778 1925 1333 2286 1354 2407 1574 2000 872 406 2303 713 863 1162 991 469 270 1019 395 891 2408 1147 2227 1602 1507 2348 463 770 2412 1775 592 1728 2343 1281 1623 2307 1744 2082 2098 2168 1181 602 938 1496 1302 290 2479 1628 827 820 2109 2207 887 1836 367 1980 481 1352 981 1946 1535 1208 1742 1121 466 866 468 2071 2463 1626 1432 1525 766 1634 1861 659 549 628 2492 574 1265 1097 844 771 2344 1286 1710 484 360 1940 2271 1961 1221 796 2005 1239 494 2465 998 1307 202 618 649 1150 1173 339 2137 2306 804 548 1819 789 1142 1915 452 2056 268 2150 1931 675 1224 2166 1479 948 1487 2346 398 2024 821 729 947 1470 1855 566 822 2212 1433 1119 390 1702 1078 926 1740 454 531 931 1811 1269 225 300 937 1323 2235 1100 1178 1656 1603 1852 1873 378 1199 2213 2270 859 1435 968 1062 809 951 1701 1791 2494 694 1763 289 1785 676 1697 1779 1798 1409 267 1712 728 642 1268 664 1455 1545 814 1406 1844 836 881 2439 1541 2478 1240 1113 1571 897 2139 1840 1917 1228 1405 1657 1404 662 2204 811 2092 1919 2224 738 1146 1663 283 2052 955 1601 2258 341 1217 2132 673 1758 1802 1548 2457 567 2356 428 2374 1387 1863 1179 1298 478 377 337 2329 1296 1252 1055 287 1502 2489 1084 1107 973 1176 493 1736 900 682 1847 417 606 1185 923 1396 1617 1329 1397 714 1587 832 2153 340 1209 1427 2335 2290 922 1975 2475 2228 324 1886 2154 2327 1739 449 1273 800 2196 783 2142 2470 422 929 1104 496 2431 1460 984 303 401 491 1253 621 1029 564 382 697 1314 1378 2079 1478 1826 2076 2352 354 665 1358 514 1283 2205 2432 2459 1047 1497 1827 1991 2339 2089 2115 2280 1549 1808 527 2488 672 1270 1839 2292 586 2145 2490 950 2300 577 2336 1604 1000 749 1952 799 1543 2040 1380 815 1751 296 2091 1279 1151 1485 1154 2483 1800 2393 2120 1403 1594 1932 1648 1687 1876 1166 2427 1175 2178 580 698 1883 999 364 884 2259 1869 1804 1414 1249 2252 1576 560 1091 1668 1829 1394 1765 1022 828 1658 552 1990 960 1310 776 598 557 813 2326 356 266 1235 1688 711 1854 2093 1878 2360 537 1363 2391 2422 748 1667 723 1814 1531 1890 868 1065 841 516 826 2106 1735 1081 1962 2022 1930 885 1555 1572 886 1385 1641 2460 1437 2199 722 1948 818 1450 443 1306 476 1423 1005 568 1359 1491 349 972 475 925 2416 294 648 330 462 855 1493 1335 1905 1431 1907 1749 2418 1255 2171 2129 2325 1542 2065 2264 683 1936 1108 1934 2241 1001 2403 2170 2301 1170 1730 2163 1595 1973 2315 2441 376 1575 405 1864 2182 1172 1752 2254 343 399 1523 2203 274 1703 721 986 2236 1504 978 425 1164 2456 1287 627 1214 638 1691 1152 2265 1134 1011 2075 1452 2083 1035 2361 1371 927 1464 2367 487 1598 2450 2238 692 834 843 848 1261 373 684 536 875 2377 2023 508 775 2050 2389 1613 840 2230 446 1693 765 1983 979 701 1551 2041 2261 1642 1950 570 2283 1317 1369 1274 2497 759 1511 626 1342 1676 2449 1516 1518 1731 2331 1009 726 693 2448 1519 489 2223 854 1149 647 1714 895 1379 1188 696 942 1552 1821 1192 910 2380 1300 1709 416 2311 847 660 1695 2149 2419 718 429 1537 1583 1630 1680 2328 1197 1539 1512 2245 656 500 1772 1988 584 1889 1246 1561 805 1102 1679 1167 2026 754 447 2088 964 1577 725 1382 1896 1465 1456 1635 704 1941 1619 455 710 622 879 419 1367 2365 787 1633 2312 1524 2372 1875 1438 2402 409 858 1589 1353 2146 2251 740 1622 615 1053 2114 2183 515 482 1390 2140 1187 430 689 1755 2100 2185 1732 2037 2337 1823 1828 1926 2188 1442 1156 2229 1528 2342 643 644 1698 2366 1851 483 825 2468 2216 1247 1860 1420 1277 1774 2164 569 1205 709 1026 902 724 1087 1083 1160 1376 1430 612 1303 1796 679 2469 1722 635 1725 953 1750 278 1315 1865 2316 1929 1773 2480 1258 751 1159 1063 263 1106 2446 1631 2039 2394 681 1753 2108 471 1898 388 411 2029 705 1410 2165 2008 2211 1684 666 2333 1506 448 1050 2430 1198 1180 1165 305 687 762 1085 2232 989 1510 1503 488 1278 2220 523 565 1982 1370 2414 522 2038 1077 1177 1993 2357 2396 2276 2500 803 1289 1977 1933 1200 2330 2001 2019 2384 588 735 1061 930 2225 1014 456 2289 744 1275 1459 1017 2192 2031 1938 2020 2117 1025 526 992 1544 368 2444 963 630 1788 1882 1767 418 203 1024 1607 2226 393 1786 1517 1079 700 596 1272 1874 1759 1089 2338 975 1322 1673 1425 1570 451 778 908 1137 1792 1924 2279 1738 1220 1582 1599 372 1328 1408 1920 1711 1901 326 1074 1568 906 2314 1795 2323 1316 1453 1098 1737 1979 2157 2189 2197 2096 1326 2054 336 940 1559 412 2297 893 2136 957 301 1632 1027 1122 2110 1923 379 1305 432 1126 442 1020 1700 599 737 2011 578 1754 1213 2362 785 2103 1334 2250 1716 2481 610 2285 1184 1355 1232 915 874 919 2304 797 1690 1140 835 2395 1616 322 402 632 1263 1868 2491 1360 2167 605 1770 1996 2378 359 1124 1291 581 1473 542 1809 434 2399 2233 502 873 1211 1103 1588 1313 2257 279 1921 1969 1230 2081 193 1970 2105 2043 2090 1136 1037 1127 1229 1771 513 1671 1783 1564 2206 1484 1812 403 971 1013 1284 2405 817 889 329 1769 2287 2095 1434 1699 1718 2382 2466 427 2415 1818 1881 1040 1520 2487 1981 1282 1745 1256 371 932 2281 433 1500 2210 977 328 853 1600 2426 1111 1790 974 824 1033 1848 1706 1614 2134 1490 2364 2131 1073 888 1392 917 1968 1093 555 503 505 1606 2155 2455 1129 2222 1381 823 2237 2243 1655 1853 435 2209 346 534 667 2454 2268 883 768 1692 385 1276 1942 2078 2433 1654 2288 2218 1533 1636 941 507 1522 1311 1357 2175 2006 1294 2122 2194 2169 351 1756 1157 952 2429 532 342 1349 2462 2195 407 758 1372 306 784 1987 2351 2464 965 2231 369 450 2278 1951 1319 1640 1130 1837 284 1461 2400 2368 2482 935 453 1451 2111 2485 903 1457 1830 2113 2097 2293 1927 1002 2063 1761 876 678 1095 539 2003 1271 2324 1010 1341 1416 1182 2409 520 1194 1426 1125 2435 1637 420 593 538 1558 617 2127 1590 1264 2458 708 375 2172 985 1058 2072 1060 2010 2007 1365'

In [89]:
with open('submission5.txt', 'w') as s5:
  s5.write(" ".join(sorted_temp))

files.download('submission5.txt')

# LEVEL 2